### PR TITLE
Remove dependency on deprecated libnx hid API

### PR DESCRIPTION
**Pull request by SundayReds**
Replace deprecated `hid.h` API with newer supported `pad.h` API to prevent errors with newer versions of libnx.

Issue #8

### CODE REVIEW

**Comment by caseif** [comment]
Thanks for the contribution! I'll verify this on hardware this weekend if I have the time and then get it merged.

**Comment by KP2048** [comment]
this will no longer matter with the gui as borealis handles this already

**Comment by SundayReds** [comment]
When I ran into this `hid` error, I actually went on to compile the repos of every single person who forked from this original project (including yours) before realizing it was due to deprecated APIs. I remember yours quite well because it came with the borealis GUI and was the only one that actually built because you shifted the dependency to borealis. I really liked it and thought it was pretty great, but maybe I could share my feedback of it here.

I ultimately chose to continue making personal modifications using the original console-style that caseif made the app in because:

1. Even though the GUI looked nice, it couldn't display my entire list of mods at once (I only have about 14) using the card style display, whereas the console could easily fit more if it needed to.
2. It's way easier to see the load order and which mods are toggled-on in the console, maybe because of the colour and contrast. Also, being able to see the entire list helped too. 
3. The console loads up faster, and is generally snappier to use.

However, I'm in engineering/computation so maybe my views are biased more towards console cause I'm used to it. It's possible that other people would prefer the GUI.

PS, because you changed the button mappings for exiting the app (to B, if I recall properly) and saving the app, some of your system messages and display needs to be corrected

**Comment by KP2048** [comment]
The button mappings, contrast, and status messages stuff can be fixed. The not being able to see everything at once, not so much. I can’t compress the GUI anymore than it already is bc of limitations of borealis. If you want I can try to add a button that switches between GUI and console?

**Comment by KP2048** [comment]
ok when i put the console ui back as an optional feature, i made it use the updated api.

**Comment by caseif** [comment]
LGTM, thanks again for this!

**Pull request merged**
