### PR TITLE
GUI and SimpleModManager plugin

### PR DESCRIPTION
**Pull request by KP2048**

### CODE REVIEW

**Comment by KP2048** [comment]
Also this is the first SMM plugin in existence because the pr that i made that adds the plugin loading hasn't been merged yet

**Comment by KP2048** [comment]
https://github.com/nadrino/SimpleModManager/pull/17

**Comment by caseif** [comment]
Sorry, this somehow slipped under my radar when you first submitted it.

I can't accept this PR in its current state - it would need to be split into multiple different PRs given that it does a number of different things (adding a GUI, SMM plugin-ifying, updating README, adding a Dockerfile). There are also a lot of stylistic changes and example code that would need to be scrubbed out.

That all being said I'd still be interested in merging the GUI changes (and maybe the plugin-ifying) if you resubmit them as a standalone PR, but I realize the changes I'm requesting here are a lot of work so I understand if you'd rather not submit them into upstream.

**Comment by KP2048** [comment]
I’d be willing to split things, but I honestly haven’t looked at this for a while so I’d have to look through it and stuff

**Comment by KP2048** [comment]
pr split

**Pull request closed without merging**
